# Generated by Django 4.2.16 on 2024-09-23 04:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0007_remove_sasinfo_description_alter_aboutus_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='testimonials/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
